---
# - name: get hostname
#   command: hostname
#   register: hostname

- name: write_run_ansible_script
  template:
    src: run-ansible.sh.j2
    dest: ~/run-ansible.sh
    mode: 755

- name: write_run_inspec_script
  template:
    src: run-inspec.sh.j2
    dest: ~/run-inspec.sh
    mode: 755

# Example of writing yml file and including it as ansible vars
- name: write_test_var_file
  template:
    src: test_var_file.yml.j2
    dest: "test_var_file.yml"
    mode: 755

- name: include_test_file_vars
  include_vars: "test_var_file.yml"

- name: show_var_file_contents
  debug:
    msg: "{{ level1 }}"
