---
# - name: get hostname
#   command: hostname
#   register: hostname

- name: write_run_ansible_script
  template:
    src: run-ansible.sh.j2
    dest: ~/run-ansible.sh
    mode: 755

- name: write_run_inspec_script
  template:
    src: run-inspec.sh.j2
    dest: ~/run-inspec.sh
    mode: 755
