---
# - name: get hostname
#   command: hostname
#   register: hostname

- name: write_run_ansible_script
  template:
    src: run-ansible.sh.j2
    dest: ~/run-ansible.sh
    mode: 755

- name: write_run_inspec_script
  template:
    src: run-inspec.sh.j2
    dest: ~/run-inspec.sh
    mode: 755

- name: write_test_var_file
  template:
    src: test_var_file.yml.j2
    dest: "{{ inspec_exec_directory }}/test_var_file.yml"
    mode: 755
