---
- name: Download RPM package
  get_url:
    url: "https://downloads.cinc.sh/files/stable/cinc-auditor/{{ inspec_version }}/el/9/cinc-auditor-{{ inspec_version }}-1.el9.x86_64.rpm"
    dest: /tmp/cinc-auditor-{{ inspec_version }}-1.el9.x86_64.rpm

- name: Install inspec from RPM
  yum:
    name: /tmp/cinc-auditor-{{ inspec_version }}-1.el9.x86_64.rpm
    state: present
    disable_gpg_check: true  # Disable GPG signature check
  become: true

- name: Create inspec directory
  file: 
    path: "{{ inspec_exec_directory }}"
    state: directory

- name: Write inspec config file
  template:
    src: "config.json.j2"
    dest: "{{ inspec_exec_directory }}/config.json"
    force: true

